host: http://localhost
status: available
port: 8080
env: development
db:
  maxOpenConns: 30
  maxIdleConns: 10
  maxIdleTime: 10m
  dsn: <DSN>
logger:
  need_debug: true
limiter:
  rps: 4
  burst: 8
  enabled: true
smtp:
  host: smtp.mailtrap.io
  port: 2525
  user: 179f53d6893b87
  sender: Paste <no-reply>
  password: <PASSWORD>
  timeout: 5s
cors:
  trustedOrigins: ["https://zhukovrost.github.io/pasteAPI/*", "http://localhost:8080/*"]
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  timeout: 5s
  expiration: 15m
#rabbitmq:
#  url:
#  wait_time: 5s
#  attempts: 5
#  exchange: emails
#  exchange_type: direct
#  queue: user_emails