host: 0.0.0.0
status: available
port: 8080
env: development
db:
  maxOpenConns: 30
  maxIdleConns: 10
  maxIdleTime: 10m
  dsn: postgres://pasteadmin:admin@localhost:5432/paste?sslmode=disable
logger:
  need_debug: true
limiter:
  rps: 4
  burst: 8
  enabled: true
cors:
  trustedOrigins: ["https://zhukovrost.github.io", "http://localhost:8080", "http://localhost:8081", "http://localhost", "http://localhost:80"]
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  expiration: 15m
rabbitmq:
  url: amqp://guest:guest@localhost:5672/
  exchange: emails
  exchange_type: direct
  queue: user_emails
activation_link: http://localhost:8081/activate?token=
reset_link: http://localhost:8081/password_reset?token=